version: '3.7'

services:
  php:
    build:
      context: ./
      dockerfile: docker/php/dev.Dockerfile
      args:
        - HOST_UID=${HOST_UID}
    depends_on:
      - db
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    expose:
      - "9000"
    environment:
      - COMPOSER_HOME=/var/www/html/var/composer
      - PHP_IDE_CONFIG
      - XDEBUG_ENABLED
      - XDEBUG_MODE
      - XDEBUG_SESSION
      - XDEBUG_CONFIG
      - APP_ENV
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/dev.Dockerfile
      args:
        - HOST_UID=${HOST_UID}
    depends_on:
      - php
    ports:
      - "${EXTERNAL_HTTP_PORT-80}:80"
    volumes:
      - .:/var/www/html
      - ./var/log:/var/log/nginx
    environment:
      - PHP_UPSTREAM=php:9000
  db:
    image: postgres:12.2
    ports:
      - "${EXTERNAL_DB_PORT-5432}:5432"
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB-dev}
      - POSTGRES_USER=${POSTGRES_USER-dev}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD-dev}

volumes:
  db: